resolver: lts-16.20
allow-newer: true

packages:
- core/schema
- core/rpc
- core/optics
- core/lens
- adapter/avro
- adapter/protobuf
- adapter/persistent
- adapter/kafka
- grpc/common
- grpc/client
- grpc/server
- graphql
- servant/server
- instrumentation/prometheus
- instrumentation/tracing
- examples/health-check
- examples/library
- examples/route-guide
- examples/seed
- examples/todolist
- examples/with-persistent
- compendium-client

extra-deps:
- http2-client-0.9.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.2.0
- warp-grpc-0.4.0.1
- hw-kafka-client-3.1.1
- hw-kafka-conduit-2.7.0
- tracing-control-0.0.6
- wai-middleware-prometheus-1.0.0
- graphql-0.11.0.0
- generic-aeson-0.2.0.11
- parameterized-0.5.0.0
# Dropped in LTS 16
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- stm-lifted-2.5.0.0
# Updated servant
- servant-0.18
- servant-client-core-0.18
- servant-client-0.18
- servant-server-0.18
- servant-swagger-1.1.10
