resolver: lts-16.3
allow-newer: true

packages:
- core/schema
- core/rpc
- core/optics
- adapter/avro
- adapter/protobuf
- adapter/persistent
- adapter/kafka
- grpc/common
- grpc/client
- grpc/server
- graphql
- instrumentation/prometheus
- instrumentation/tracing
- examples/health-check
- examples/route-guide
- examples/seed
- examples/todolist
- examples/with-persistent
- compendium-client

extra-deps:
- git: https://github.com/serras/tracing.git
  commit: affcb9459db84692b7cfb4759aebb655279e61bc
- http2-client-0.9.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.1.0
- warp-grpc-0.4.0.1
- hw-kafka-client-3.1.1
- hw-kafka-conduit-2.7.0
- wai-middleware-prometheus-1.0.0
- git: https://github.com/hasura/graphql-parser-hs.git
  commit: f4a093981ca5626982a17c2bfaad047cc0834a81
# Dropped in LTS 16
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- stm-lifted-2.5.0.0
