resolver: lts-15.0
allow-newer: true

packages:
- core/schema
- core/rpc
- core/optics
- adapter/avro
- adapter/protobuf
- adapter/persistent
- adapter/kafka
- grpc/common
- grpc/client
- grpc/server
- examples/health-check/avro
- examples/health-check/protobuf
- examples/route-guide
- examples/seed/avro
- examples/seed/protobuf
- examples/todolist
- examples/with-persistent
- compendium-client

extra-deps:
- http2-client-0.9.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.1.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.3.0.0
- http2-client-grpc-0.8.0.0
# - avro-0.4.6.0
- git: https://github.com/haskell-works/avro.git
  commit: 93bc12fdb807e9567ef113ed71c7b3487516a371
# - language-avro-0.1.0.0
- git: https://github.com/higherkindness/avro-parser-haskell.git
  commit: c8f7497766d0d1be8579fb03b302340adafeaf49
- hw-kafka-client-3.0.0
- hw-kafka-conduit-2.6.0
- HasBigDecimal-0.1.1
