resolver: lts-14.27
allow-newer: true

packages:
- core/schema
- core/rpc
- core/optics
- adapter/avro
- adapter/protobuf
- adapter/persistent
- adapter/kafka
- grpc/common
- grpc/client
- grpc/server
- graphql
- examples/health-check
- examples/route-guide
- examples/seed
- examples/todolist
- examples/with-persistent
- compendium-client

extra-deps:
- http2-client-0.9.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.1.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.4.0.0
- http2-client-grpc-0.8.0.0
- avro-0.4.7.0
- language-protobuf-1.0.1
- language-avro-0.1.2.0
- hw-kafka-client-3.0.0
- hw-kafka-conduit-2.6.0
- HasBigDecimal-0.1.1
- regex-base-0.94.0.0
- regex-tdfa-1.3.1.0
- git: https://github.com/hasura/graphql-parser-hs.git
  commit: 1380495a7b3269b70a7ab3081d745a5f54171a9c
- wai-route-1.0.0
- pattern-trie-0.1.0
# missing in the current LTS
- primitive-0.7.0.0
- primitive-extras-0.8
- primitive-unlifted-0.1.2.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- AC-Angle-1.0
- optics-core-0.2
- indexed-profunctors-0.1

