resolver: lts-18.28
allow-newer: true

packages:
- adapter/avro
- adapter/kafka
- adapter/persistent
- adapter/protobuf
- compendium-client
- core/lens
- core/optics
- core/rpc
- core/schema
- examples/health-check
- examples/library/backend
- examples/route-guide
- examples/seed
- examples/todolist
- examples/with-persistent
- graphql
- grpc/client
- grpc/common
- grpc/server
- instrumentation/prometheus
- instrumentation/tracing
- servant/server

extra-deps:
- http2-2.0.6
- warp-3.3.14
- http2-client-0.10.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- warp-grpc-0.4.0.1
- hw-kafka-conduit-2.7.0
- graphql-1.0.3.0
- stm-hamt-1.2.0.7
- stm-containers-1.2
- tracing-0.0.7.2
- tracing-control-0.0.7.3
