resolver: lts-14.14

packages:
- core/schema
- core/rpc
- adapter/avro
- adapter/protobuf
- grpc/client
- grpc/server
- examples/health-check
- examples/route-guide
- examples/seed
- examples/todolist
- examples/with-persistent
- compendium-client

extra-deps:
- http2-client-0.9.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.0.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.2.0.0
- http2-client-grpc-0.8.0.0
- avro-0.4.5.4
- language-protobuf-1.0
# missing in the current LTS
- primitive-0.7.0.0
- primitive-extras-0.8
- primitive-unlifted-0.1.2.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- AC-Angle-1.0
