resolver: lts-14.22
allow-newer: true
extra-deps:
# mu
- mu-schema-0.1.0.0
- mu-rpc-0.1.0.0
- mu-protobuf-0.1.0.0
- mu-grpc-server-0.1.0.1
- compendium-client-0.2.0.0
# dependencies of mu
- http2-client-0.9.0.0
- http2-grpc-types-0.5.0.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.3.0.0
- proto3-wire-1.1.0
- language-protobuf-1.0.1
