title: Mu-Haskell
#-------------------------
name: Mu-Haskell
#-------------------------
description: Lorem ipusm
#-------------------------
author: 47 Degrees
keywords: functional-programming, monads, monad-transformers, functional-data-structure, swift, bow, fp-types, adt, free-monads, tagless-final, mtl, for-comprehension, category-theory
#-------------------------
url: https://www.47deg.com
#-------------------------
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
    sourcemap: never
#-------------------------
permalink: pretty
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
#-------------------------
